import 'server-only';

import type { SupabaseClient } from '@supabase/supabase-js';
import type {
    BotMode,
    QueueStatus,
    ActionType,
    TargetTable,
    BotPersona,
    QueueItem,
    TargetContext,
    RunOptions,
    RunResult,
} from './types';
import { clampLimit, pick, randomishOffset, sanitizeContent } from './text';

const DEFAULT_MODEL = 'gpt-4o-mini';
const AUTO_BATCH_ID = process.env.BOT_ENGAGEMENT_BATCH_ID || 'bot-engagement-auto';

function buildFallbackDraft(item: QueueItem, persona: BotPersona | null, target: TargetContext | null) {
    const county = persona?.county || target?.county || 'my county';
    const options: Record<ActionType, string[]> = {
        social_comment: [
            `This is useful for youth in ${county}. A simple ward-level update would make follow-up easier.`,
            `Apo sawa. The main thing is making the next step clear so people know who to ask.`,
            `Hii ni muhimu. Information should reach youth early, not after decisions are already made.`,
        ],
        poll_comment: [
            `This policy needs a short youth-friendly summary before more people can respond meaningfully.`,
            `Can the final brief show county differences? That would make the results more useful.`,
            `Good question. I would also want to know what action comes after the poll closes.`,
        ],
        fund_comment: [
            `Wantam see the breakdown in simple language, especially what reached wards directly.`,
            `The fund page is helpful, but timelines and eligibility rules should be clearer for first-time applicants.`,
            `Youth need to know whether support is training, equipment, or cash before applying.`,
        ],
        project_update: [
            `Community feedback from ${county}: people support the project, but timelines and contact details need to be clearer.`,
            `The project looks promising. A public milestone update would help youth track progress properly.`,
            `Visited conversations around this project show one gap: residents want ward-level implementation updates.`,
        ],
    };

    return pick(options[item.action_type], randomishOffset());
}

async function ensureAutoBatch(supabase: SupabaseClient) {
    const { error } = await supabase.from('synthetic_demo_batches').upsert({
        id: AUTO_BATCH_ID,
        description: 'Automated synthetic bot engagement generated by the cron queue',
        requested_user_count: 0,
        requested_engagement_count: 0,
        status: 'running',
        metadata: {
            source: 'synthetic_demo',
            visibility: 'demo_only',
            created_for: 'platform_seed_data',
            generated_by_bot: true,
            note: 'Synthetic demo engagement. Exclude from real-user analytics unless explicitly included.',
        },
    }, { onConflict: 'id' });

    if (error) throw new Error(`Unable to ensure bot batch: ${error.message}`);
}

async function getPersonas(supabase: SupabaseClient, limit = 80): Promise<BotPersona[]> {
    const { data, error } = await supabase
        .from('profiles')
        .select('id, full_name, username, county, bio, learning_interests, focus_path')
        .eq('is_bot', true)
        .eq('role', 'user')
        .order('created_at', { ascending: false })
        .limit(limit);

    if (error) throw new Error(`Unable to load bot personas: ${error.message}`);
    return data || [];
}

async function getTargetContexts(supabase: SupabaseClient): Promise<TargetContext[]> {
    const [postsResult, pollsResult, fundsResult, projectsResult] = await Promise.all([
        supabase
            .from('social_posts')
            .select('id, content, created_at, profiles:user_id(county)')
            .order('created_at', { ascending: false })
            .limit(30),
        supabase
            .from('policy_polls')
            .select('id, title, description, category, status, created_at')
            .eq('status', 'active')
            .order('created_at', { ascending: false })
            .limit(20),
        supabase
            .from('public_funds')
            .select('id, title, description, sector, status, created_at')
            .order('created_at', { ascending: false })
            .limit(20),
        supabase
            .from('public_projects')
            .select('id, title, description, location_name, milestone, project_type, created_at')
            .order('created_at', { ascending: false })
            .limit(20),
    ]);

    for (const result of [postsResult, pollsResult, fundsResult, projectsResult]) {
        if (result.error) throw new Error(result.error.message);
    }

    const posts = (postsResult.data || []).map((post: any): TargetContext => ({
        id: post.id,
        table: 'social_posts',
        title: 'Community feed post',
        body: post.content,
        county: post.profiles?.county,
        extra: { action_type: 'social_comment' },
    }));

    const polls = (pollsResult.data || []).map((poll: any): TargetContext => ({
        id: poll.id,
        table: 'policy_polls',
        title: poll.title,
        body: poll.description || poll.category || 'Policy Pulse discussion',
        extra: { action_type: 'poll_comment', category: poll.category },
    }));

    const funds = (fundsResult.data || []).map((fund: any): TargetContext => ({
        id: fund.id,
        table: 'public_funds',
        title: fund.title,
        body: fund.description || fund.sector || 'Youth fund transparency discussion',
        extra: { action_type: 'fund_comment', sector: fund.sector },
    }));

    const projects = (projectsResult.data || []).map((project: any): TargetContext => ({
        id: project.id,
        table: 'public_projects',
        title: project.title,
        body: project.description || project.location_name || 'Community project monitoring update',
        county: project.location_name,
        extra: {
            action_type: 'project_update',
            milestone: project.milestone,
            project_type: project.project_type,
        },
    }));

    return [...posts, ...polls, ...funds, ...projects];
}

function actionForTarget(target: TargetContext): ActionType {
    if (target.table === 'social_posts') return 'social_comment';
    if (target.table === 'policy_polls') return 'poll_comment';
    if (target.table === 'public_funds') return 'fund_comment';
    return 'project_update';
}

async function planQueueItems(supabase: SupabaseClient, limit: number) {
    const [personas, targets] = await Promise.all([
        getPersonas(supabase),
        getTargetContexts(supabase),
    ]);

    if (personas.length === 0 || targets.length === 0) return 0;

    const offset = randomishOffset();
    const rows = Array.from({ length: limit }, (_, index) => {
        const target = pick(targets, index, offset);
        const persona = pick(personas, index, offset + 11);
        const scheduled = new Date(Date.now() + index * 90 * 1000);

        return {
            persona_user_id: persona.id,
            target_table: target.table,
            target_record_id: target.id,
            action_type: actionForTarget(target),
            status: 'pending',
            scheduled_for: scheduled.toISOString(),
            metadata: {
                target_title: target.title,
                target_body_excerpt: target.body.slice(0, 260),
                target_county: target.county || null,
                persona_county: persona.county,
                persona_interests: persona.learning_interests || [],
                source: 'synthetic_demo',
                visibility: 'demo_only',
                created_for: 'platform_seed_data',
                generated_by_bot: true,
            },
        };
    });

    const { data, error } = await supabase
        .from('bot_engagement_queue')
        .insert(rows)
        .select('id');

    if (error) throw new Error(`Unable to plan queue items: ${error.message}`);
    return data?.length || 0;
}

async function loadDueQueueItems(supabase: SupabaseClient, status: QueueStatus, limit: number): Promise<QueueItem[]> {
    const { data, error } = await supabase
        .from('bot_engagement_queue')
        .select('*')
        .eq('status', status)
        .lte('scheduled_for', new Date().toISOString())
        .order('scheduled_for', { ascending: true })
        .limit(limit);

    if (error) throw new Error(`Unable to load ${status} queue items: ${error.message}`);
    return data || [];
}

async function loadPersona(supabase: SupabaseClient, id: string | null): Promise<BotPersona | null> {
    if (!id) return null;
    const { data, error } = await supabase
        .from('profiles')
        .select('id, full_name, username, county, bio, learning_interests, focus_path')
        .eq('id', id)
        .maybeSingle();
    if (error) throw new Error(`Unable to load persona: ${error.message}`);
    return data;
}

async function loadTarget(supabase: SupabaseClient, item: QueueItem): Promise<TargetContext | null> {
    if (item.target_table === 'social_posts') {
        const { data, error } = await supabase
            .from('social_posts')
            .select('id, content, profiles:user_id(county)')
            .eq('id', item.target_record_id)
            .maybeSingle();
        if (error) throw new Error(error.message);
        if (!data) return null;
        return { id: data.id, table: 'social_posts', title: 'Community feed post', body: data.content, county: (data as any).profiles?.county };
    }

    if (item.target_table === 'policy_polls') {
        const { data, error } = await supabase
            .from('policy_polls')
            .select('id, title, description, category')
            .eq('id', item.target_record_id)
            .maybeSingle();
        if (error) throw new Error(error.message);
        if (!data) return null;
        return { id: data.id, table: 'policy_polls', title: data.title, body: data.description || data.category || '' };
    }

    if (item.target_table === 'public_funds') {
        const { data, error } = await supabase
            .from('public_funds')
            .select('id, title, description, sector')
            .eq('id', item.target_record_id)
            .maybeSingle();
        if (error) throw new Error(error.message);
        if (!data) return null;
        return { id: data.id, table: 'public_funds', title: data.title, body: data.description || data.sector || '' };
    }

    const { data, error } = await supabase
        .from('public_projects')
        .select('id, title, description, location_name, milestone')
        .eq('id', item.target_record_id)
        .maybeSingle();
    if (error) throw new Error(error.message);
    if (!data) return null;
    return { id: data.id, table: 'public_projects', title: data.title, body: data.description || data.location_name || '', county: data.location_name, extra: { milestone: data.milestone } };
}

function parseOpenAiJson(text: string) {
    const cleaned = text.trim().replace(/^```(?:json)?/i, '').replace(/```$/g, '').trim();
    const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
    return JSON.parse(jsonMatch ? jsonMatch[0] : cleaned);
}

async function draftWithLlm(item: QueueItem, persona: BotPersona | null, target: TargetContext | null) {
    const apiKey = process.env.OPENAI_API_KEY;
    const model = process.env.BOT_ENGAGEMENT_MODEL || DEFAULT_MODEL;

    if (!apiKey) {
        return {
            content: buildFallbackDraft(item, persona, target),
            model,
            safetyNotes: 'Fallback template used because OPENAI_API_KEY is not configured.',
        };
    }

    const system = [
        'You generate synthetic demo engagement for Kiongozi, a Kenyan youth civic-tech learning platform.',
        'The output is demo-only and must never claim to be real official information.',
        'Write like a Kenyan youth participant: natural Kenyan English, light Kiswahili or Sheng only when it fits.',
        'Avoid defamation, hate speech, political extremism, private data, unsupported accusations, and named-person allegations.',
        'Keep it concise, constructive, and specific to the target context.',
        'Return strict JSON only: {"content":"...","safety_notes":"..."}',
    ].join(' ');

    const user = {
        action_type: item.action_type,
        persona: {
            name: persona?.full_name,
            county: persona?.county,
            bio: persona?.bio,
            interests: persona?.learning_interests,
            focus_path: persona?.focus_path,
        },
        target: {
            table: target?.table,
            title: target?.title,
            body: target?.body?.slice(0, 700),
            county: target?.county,
            extra: target?.extra,
        },
        rules: [
            '12 to 55 words.',
            'Do not use hashtags.',
            'Do not use full stops or periods.',
            'It is okay to include one small natural typo occasionally, like a real casual comment.',
            'Do not say you are AI or a bot.',
            'Do not invent numbers, dates, names, or official claims.',
            'For project updates, frame as community feedback unless direct evidence is present.',
        ],
    };

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
            model,
            temperature: 0.72,
            max_tokens: 180,
            response_format: { type: 'json_object' },
            messages: [
                { role: 'system', content: system },
                { role: 'user', content: JSON.stringify(user) },
            ],
        }),
    });

    if (!response.ok) {
        const body = await response.text();
        throw new Error(`OpenAI request failed (${response.status}): ${body.slice(0, 300)}`);
    }

    const data = await response.json();
    const raw = data.choices?.[0]?.message?.content || '{}';
    const parsed = parseOpenAiJson(raw);

    return {
        content: sanitizeContent(String(parsed.content || '')),
        model,
        safetyNotes: String(parsed.safety_notes || 'LLM generated; policy prompt applied.').slice(0, 500),
    };
}

function validateDraft(content: string) {
    const cleaned = sanitizeContent(content);
    if (cleaned.length < 8) return { ok: false, content: cleaned, reason: 'Draft too short.' };
    if (/(?:i am an ai|as an ai|bot account|synthetic demo)/i.test(cleaned)) {
        return { ok: false, content: cleaned, reason: 'Draft exposed bot/synthetic framing.' };
    }
    if (/(?:stole|thief|corrupt|tribe|kill|attack)/i.test(cleaned)) {
        return { ok: false, content: cleaned, reason: 'Draft contained unsafe accusation or violence language.' };
    }
    return { ok: true, content: cleaned, reason: null };
}

async function draftPendingItems(supabase: SupabaseClient, items: QueueItem[]) {
    let drafted = 0;
    let failed = 0;

    for (const item of items) {
        try {
            const [persona, target] = await Promise.all([
                loadPersona(supabase, item.persona_user_id),
                loadTarget(supabase, item),
            ]);

            if (!target) {
                await supabase.from('bot_engagement_queue').update({
                    status: 'skipped',
                    error_message: 'Target record no longer exists.',
                    updated_at: new Date().toISOString(),
                }).eq('id', item.id);
                continue;
            }

            const draft = await draftWithLlm(item, persona, target);
            const validation = validateDraft(draft.content);
            if (!validation.ok) {
                failed += 1;
                await supabase.from('bot_engagement_queue').update({
                    status: 'failed',
                    draft_content: validation.content,
                    error_message: validation.reason,
                    model_used: draft.model,
                    safety_notes: draft.safetyNotes,
                    generated_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                }).eq('id', item.id);
                continue;
            }

            const { error } = await supabase.from('bot_engagement_queue').update({
                status: 'drafted',
                draft_content: validation.content,
                model_used: draft.model,
                safety_notes: draft.safetyNotes,
                generated_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
            }).eq('id', item.id);

            if (error) throw error;
            drafted += 1;
        } catch (error: any) {
            failed += 1;
            await supabase.from('bot_engagement_queue').update({
                status: 'failed',
                error_message: error.message || 'Draft failed.',
                updated_at: new Date().toISOString(),
            }).eq('id', item.id);
        }
    }

    return { drafted, failed };
}

async function labelPublishedRecord(
    supabase: SupabaseClient,
    tableName: string,
    recordId: string,
    personaUserId: string | null,
    metadata: Record<string, any>,
) {
    await ensureAutoBatch(supabase);

    const { error } = await supabase.from('synthetic_demo_records').upsert({
        batch_id: AUTO_BATCH_ID,
        table_schema: 'public',
        table_name: tableName,
        record_id: recordId,
        record_key: recordId,
        persona_user_id: personaUserId,
        is_seed_data: true,
        source: 'synthetic_demo',
        visibility: 'demo_only',
        created_for: 'platform_seed_data',
        replace_with_real_activity: true,
        metadata: {
            ...metadata,
            generated_by_bot: true,
            source: 'synthetic_demo',
            visibility: 'demo_only',
        },
    }, { onConflict: 'table_schema,table_name,record_key' });

    if (error) throw new Error(`Synthetic label failed: ${error.message}`);
}

async function publishItem(supabase: SupabaseClient, item: QueueItem) {
    if (!item.draft_content?.trim()) throw new Error('Cannot publish an empty draft.');

    const content = sanitizeContent(item.draft_content);
    let tableName: string;
    let published: any;

    if (item.action_type === 'social_comment') {
        tableName = 'social_comments';
        const { data, error } = await supabase.from(tableName).insert({
            post_id: item.target_record_id,
            user_id: item.persona_user_id,
            content,
        }).select('id').single();
        if (error) throw error;
        published = data;
    } else if (item.action_type === 'poll_comment') {
        tableName = 'poll_comments';
        const { data, error } = await supabase.from(tableName).insert({
            poll_id: item.target_record_id,
            user_id: item.persona_user_id,
            content,
        }).select('id').single();
        if (error) throw error;
        published = data;
    } else if (item.action_type === 'fund_comment') {
        tableName = 'fund_comments';
        const { data, error } = await supabase.from(tableName).insert({
            fund_id: item.target_record_id,
            user_id: item.persona_user_id,
            content,
            comment_type: 'comment',
        }).select('id').single();
        if (error) throw error;
        published = data;
    } else {
        tableName = 'project_updates';
        const { data, error } = await supabase.from(tableName).insert({
            project_id: item.target_record_id,
            submitted_by: item.persona_user_id,
            content,
            update_type: 'progress',
        }).select('id').single();
        if (error) throw error;
        published = data;
    }

    await labelPublishedRecord(supabase, tableName, published.id, item.persona_user_id, {
        bot_queue_id: item.id,
        target_table: item.target_table,
        target_record_id: item.target_record_id,
        interaction_type: item.action_type,
    });

    const { error: updateError } = await supabase.from('bot_engagement_queue').update({
        status: 'published',
        published_table_name: tableName,
        published_record_key: published.id,
        published_record_id: published.id,
        published_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }).eq('id', item.id);

    if (updateError) throw updateError;
}

async function publishItems(supabase: SupabaseClient, items: QueueItem[]) {
    let published = 0;
    let failed = 0;

    for (const item of items) {
        try {
            await publishItem(supabase, item);
            published += 1;
        } catch (error: any) {
            failed += 1;
            await supabase.from('bot_engagement_queue').update({
                status: 'failed',
                error_message: error.message || 'Publish failed.',
                updated_at: new Date().toISOString(),
            }).eq('id', item.id);
        }
    }

    return { published, failed };
}

export async function runBotEngagement(supabase: SupabaseClient, options: RunOptions = {}): Promise<RunResult> {
    const limit = clampLimit(options.limit);
    const mode: BotMode = options.mode || (process.env.BOT_ENGAGEMENT_AUTO_PUBLISH === 'true' ? 'auto_publish' : 'draft');

    const { data: run, error: runError } = await supabase.from('bot_engagement_runs').insert({
        mode,
        requested_limit: limit,
        metadata: {
            auto_publish_env: process.env.BOT_ENGAGEMENT_AUTO_PUBLISH === 'true',
            model: process.env.BOT_ENGAGEMENT_MODEL || DEFAULT_MODEL,
        },
    }).select('id').single();

    if (runError) throw new Error(`Unable to create bot run: ${runError.message}`);

    let plannedCount = 0;
    let draftedCount = 0;
    let publishedCount = 0;
    let failedCount = 0;
    let skippedCount = 0;

    try {
        if (mode !== 'publish_approved' && options.planIfEmpty !== false) {
            const duePending = await loadDueQueueItems(supabase, 'pending', limit);
            if (duePending.length < limit) {
                plannedCount = await planQueueItems(supabase, limit - duePending.length);
            }
        }

        if (mode === 'publish_approved') {
            const approved = await loadDueQueueItems(supabase, 'approved', limit);
            const published = await publishItems(supabase, approved);
            publishedCount = published.published;
            failedCount += published.failed;
        } else {
            const pending = await loadDueQueueItems(supabase, 'pending', limit);
            const drafted = await draftPendingItems(supabase, pending);
            draftedCount = drafted.drafted;
            failedCount += drafted.failed;

            if (mode === 'auto_publish' && draftedCount > 0) {
                const drafts = await loadDueQueueItems(supabase, 'drafted', limit);
                const published = await publishItems(supabase, drafts);
                publishedCount = published.published;
                failedCount += published.failed;
            }
        }

        const { data: skippedRows } = await supabase
            .from('bot_engagement_queue')
            .select('id')
            .eq('status', 'skipped')
            .gte('updated_at', new Date(Date.now() - 5 * 60 * 1000).toISOString());
        skippedCount = skippedRows?.length || 0;

        await supabase.from('bot_engagement_runs').update({
            completed_at: new Date().toISOString(),
            planned_count: plannedCount,
            drafted_count: draftedCount,
            published_count: publishedCount,
            failed_count: failedCount,
            skipped_count: skippedCount,
            status: 'completed',
        }).eq('id', run.id);

        return {
            runId: run.id,
            mode,
            plannedCount,
            draftedCount,
            publishedCount,
            failedCount,
            skippedCount,
        };
    } catch (error: any) {
        await supabase.from('bot_engagement_runs').update({
            completed_at: new Date().toISOString(),
            status: 'failed',
            error_message: error.message || 'Bot engagement run failed.',
        }).eq('id', run.id);
        throw error;
    }
}

export async function approveQueueItem(supabase: SupabaseClient, id: string) {
    const { error } = await supabase
        .from('bot_engagement_queue')
        .update({ status: 'approved', updated_at: new Date().toISOString() })
        .eq('id', id)
        .eq('status', 'drafted');
    if (error) throw new Error(error.message);
}

export async function rejectQueueItem(supabase: SupabaseClient, id: string) {
    const { error } = await supabase
        .from('bot_engagement_queue')
        .update({ status: 'rejected', updated_at: new Date().toISOString() })
        .eq('id', id)
        .in('status', ['drafted', 'approved']);
    if (error) throw new Error(error.message);
}
