"use client";

/**
 * ExportModal Component
 * Simplified text-only export to match mobile app functionality
 */
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Download,
  FileText,
  MessageCircle,
  CheckCircle2,
  AlertCircle,
  Loader2
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Conversation, Message } from '../../types/chat';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  conversations: Conversation[];
  currentConversationId?: string | null;
  darkMode?: boolean;
}

interface ExportOptions {
  includeMetadata: boolean;
  includeTimestamps: boolean;
  selectedConversations: string[];
  exportAll: boolean;
}

export default function ExportModal({
  isOpen,
  onClose,
  conversations,
  currentConversationId,
  darkMode = false
}: ExportModalProps) {
  const [options, setOptions] = useState<ExportOptions>({
    includeMetadata: true,
    includeTimestamps: true,
    selectedConversations: currentConversationId ? [currentConversationId] : [],
    exportAll: conversations.length > 0 ? true : false // Default to export all if conversations exist
  });

  const [isExporting, setIsExporting] = useState(false);
  const [exportStatus, setExportStatus] = useState<'idle' | 'success' | 'error'>('idle');

  // Reset options when modal opens
  useEffect(() => {
    if (isOpen) {
      setOptions({
        includeMetadata: true,
        includeTimestamps: true,
        selectedConversations: currentConversationId ? [currentConversationId] : conversations.map(c => c.id),
        exportAll: conversations.length > 0 ? true : false // Default to export all
      });
      setExportStatus('idle');
    }
  }, [isOpen, currentConversationId, conversations]);

  // Handle escape key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = 'unset';
    };
  }, [isOpen, onClose]);

  // Simple text export format like mobile app
  const exportFormat = {
    label: 'Plain Text',
    description: 'Simple text format, easy to read and share',
    icon: FileText,
    extension: '.txt'
  };

  const handleConversationToggle = (conversationId: string) => {
    if (options.exportAll) return; // Don't allow individual selection when export all is enabled

    setOptions(prev => ({
      ...prev,
      selectedConversations: prev.selectedConversations.includes(conversationId)
        ? prev.selectedConversations.filter(id => id !== conversationId)
        : [...prev.selectedConversations, conversationId]
    }));
  };

  const handleExportAllToggle = () => {
    setOptions(prev => ({
      ...prev,
      exportAll: !prev.exportAll,
      selectedConversations: !prev.exportAll ? conversations.map(c => c.id) : []
    }));
  };

  // Simple text export function like mobile app
  const formatAsText = (conversations: Conversation[], options: ExportOptions): string => {
    const { includeTimestamps, includeMetadata } = options;
    let content = '';

    if (includeMetadata) {
      content += 'Kiongozi Platform - Conversation Export\n';
      content += `Generated on: ${new Date().toLocaleString()}\n`;
      content += `Total Conversations: ${conversations.length}\n`;
      content += '='.repeat(50) + '\n\n';
    }

    conversations.forEach((conversation, index) => {
      const title = conversation.title || `Conversation ${index + 1}`;
      content += `${title}\n`;
      content += '-'.repeat(title.length) + '\n';

      // Safe date formatting to fix "Invalid Date" issue
      if (includeTimestamps && conversation.createdAt) {
        try {
          const date = new Date(conversation.createdAt);
          if (!isNaN(date.getTime())) {
            content += `Created: ${date.toLocaleString()}\n`;
          }
        } catch (e) {
          // Skip invalid dates silently
        }
      }

      content += '\n';

      // Add basic conversation info since we don't have full messages
      if (conversation.lastMessage) {
        content += `Last message: ${conversation.lastMessage}\n`;
      }
      if (conversation.messageCount) {
        content += `Total messages: ${conversation.messageCount}\n`;
      }

      content += '\n' + '='.repeat(50) + '\n\n';
    });

    if (includeMetadata) {
      content += '\n---\nGenerated by Kiongozi Platform - Learning Management System\n';
    }

    return content;
  };

  const downloadFile = (content: string, filename: string): void => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const handleExport = async () => {
    try {
      setIsExporting(true);
      setExportStatus('idle');

      const conversationsToExport = options.exportAll
        ? conversations
        : conversations.filter(c => options.selectedConversations.includes(c.id));

      if (conversationsToExport.length === 0) {
        setExportStatus('error');
        return;
      }

      // Format as text and download
      const content = formatAsText(conversationsToExport, options);
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = conversationsToExport.length === 1
        ? `kiongozi-conversation-${conversationsToExport[0].title?.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').toLowerCase() || 'untitled'}-${timestamp}.txt`
        : `kiongozi-conversations-${conversationsToExport.length}-${timestamp}.txt`;

      downloadFile(content, filename);
      setExportStatus('success');

      // Auto close after success
      setTimeout(() => {
        onClose();
      }, 1500);
    } catch (error) {
      console.error('Export failed:', error);
      setExportStatus('error');
    } finally {
      setIsExporting(false);
    }
  };

  const selectedCount = options.exportAll ? conversations.length : options.selectedConversations.length;

  const selectedConversations = options.exportAll
    ? conversations
    : conversations.filter(c => options.selectedConversations.includes(c.id));

  const getTotalMessages = (conversations: Conversation[]): number => {
    return conversations.reduce((sum, conv) => sum + (conv.messageCount || 0), 0);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-2 sm:p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          transition={{ type: 'spring', damping: 25, stiffness: 500 }}
          className={`w-full max-w-2xl max-h-[90vh] sm:max-h-[85vh] min-h-[400px] sm:min-h-[500px] rounded-xl overflow-hidden shadow-2xl flex flex-col ${
            darkMode
              ? 'bg-gray-900 border border-gray-700'
              : 'bg-white border border-gray-200'
          }`}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className={`flex items-center justify-between p-6 border-b ${
            darkMode ? 'border-gray-700 bg-gray-800' : 'border-gray-100 bg-white'
          }`}>
            <div>
              <h2 className={`text-2xl font-bold ${
                darkMode ? 'text-white' : 'text-gray-900'
              }`}>
                Export Conversations
              </h2>
              <p className={`text-sm mt-1 ${
                darkMode ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Download your conversation history in your preferred format
              </p>
            </div>
            <button
              onClick={onClose}
              className={`w-10 h-10 rounded-full flex items-center justify-center transition-colors ${
                darkMode
                  ? 'bg-gray-700 hover:bg-gray-600 text-gray-300'
                  : 'bg-gray-100 hover:bg-gray-200 text-gray-600'
              }`}
            >
              <X size={20} />
            </button>
          </div>

          <div className="flex-1 overflow-y-auto">
            <div className="p-6 space-y-6">
              {/* Format Info - Fixed format like mobile */}
              <div>
                <h3 className={`text-lg font-semibold mb-3 ${
                  darkMode ? 'text-white' : 'text-gray-900'
                }`}>
                  Export Format: Plain Text
                </h3>
                <div className={`p-4 rounded-lg border ${
                  darkMode
                    ? 'bg-gray-800 border-gray-700'
                    : 'bg-gray-50 border-gray-200'
                }`}>
                  <div className="flex items-start gap-3">
                    <FileText size={20} className={darkMode ? 'text-gray-400' : 'text-gray-500'} />
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <span className={`font-medium ${
                          darkMode ? 'text-white' : 'text-gray-900'
                        }`}>
                          {exportFormat.label}
                        </span>
                        <span className={`text-xs px-2 py-1 rounded ${
                          darkMode ? 'bg-gray-700 text-gray-300' : 'bg-gray-100 text-gray-600'
                        }`}>
                          {exportFormat.extension}
                        </span>
                      </div>
                      <p className={`text-sm mt-1 ${
                        darkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>
                        {exportFormat.description}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Conversation Selection */}
              <div>
                <h3 className={`text-lg font-semibold mb-3 ${
                  darkMode ? 'text-white' : 'text-gray-900'
                }`}>
                  Select Conversations
                </h3>

                {/* Export All Toggle */}
                <label className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer mb-4 ${
                  darkMode
                    ? 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                    : 'bg-gray-50 border-gray-200 hover:bg-gray-100'
                }`}>
                  <input
                    type="checkbox"
                    checked={options.exportAll}
                    onChange={handleExportAllToggle}
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                  />
                  <div className="flex-1">
                    <span className={`font-medium ${
                      darkMode ? 'text-white' : 'text-gray-900'
                    }`}>
                      Export All Conversations
                    </span>
                    <p className={`text-sm ${
                      darkMode ? 'text-gray-400' : 'text-gray-600'
                    }`}>
                      Download your complete conversation history ({conversations.length} conversations)
                    </p>
                  </div>
                </label>

                {/* Individual Conversation Selection */}
                {!options.exportAll && (
                  <div className="space-y-2 max-h-64 overflow-y-auto">
                    {conversations.slice(0, 10).map((conversation) => (
                      <label
                        key={conversation.id}
                        className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-colors ${
                          options.selectedConversations.includes(conversation.id)
                            ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                            : darkMode
                              ? 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                              : 'bg-white border-gray-200 hover:bg-gray-50'
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={options.selectedConversations.includes(conversation.id)}
                          onChange={() => handleConversationToggle(conversation.id)}
                          className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                            <span className={`font-medium truncate ${
                              darkMode ? 'text-white' : 'text-gray-900'
                            }`}>
                              {conversation.title}
                            </span>
                            {conversation.id === currentConversationId && (
                              <span className="px-2 py-1 text-xs bg-green-100 text-green-700 rounded-full">
                                Current
                              </span>
                            )}
                          </div>
                          <div className="flex items-center gap-4 text-xs text-gray-500">
                            <span className="flex items-center gap-1">
                              <MessageCircle size={12} />
                              {conversation.messageCount || 0} messages
                            </span>
                            <span className="flex items-center gap-1">
                              <MessageCircle size={12} />
                              {(() => {
                                try {
                                  const date = new Date(conversation.updatedAt);
                                  return !isNaN(date.getTime()) ? date.toLocaleDateString() : 'No date';
                                } catch (e) {
                                  return 'No date';
                                }
                              })()}
                            </span>
                          </div>
                        </div>
                      </label>
                    ))}

                    {conversations.length > 10 && (
                      <p className={`text-sm text-center py-2 ${
                        darkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>
                        Showing first 10 conversations. Use "Export All" for complete history.
                      </p>
                    )}
                  </div>
                )}
              </div>

              {/* Export Options */}
              <div>
                <h3 className={`text-lg font-semibold mb-3 ${
                  darkMode ? 'text-white' : 'text-gray-900'
                }`}>
                  Include Options
                </h3>

                <div className="space-y-3">
                  <label className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer ${
                    darkMode
                      ? 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                      : 'bg-white border-gray-200 hover:bg-gray-50'
                  }`}>
                    <input
                      type="checkbox"
                      checked={options.includeTimestamps}
                      onChange={(e) => setOptions(prev => ({ ...prev, includeTimestamps: e.target.checked }))}
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <div className="flex-1">
                      <span className={`font-medium ${
                        darkMode ? 'text-white' : 'text-gray-900'
                      }`}>
                        Include Timestamps
                      </span>
                      <p className={`text-sm ${
                        darkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>
                        Add date and time information to conversations
                      </p>
                    </div>
                  </label>

                  <label className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer ${
                    darkMode
                      ? 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                      : 'bg-white border-gray-200 hover:bg-gray-50'
                  }`}>
                    <input
                      type="checkbox"
                      checked={options.includeMetadata}
                      onChange={(e) => setOptions(prev => ({ ...prev, includeMetadata: e.target.checked }))}
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <div className="flex-1">
                      <span className={`font-medium ${
                        darkMode ? 'text-white' : 'text-gray-900'
                      }`}>
                        Include Metadata
                      </span>
                      <p className={`text-sm ${
                        darkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>
                        Add export information and platform details
                      </p>
                    </div>
                  </label>
                </div>
              </div>

              {/* Export Status */}
              {exportStatus !== 'idle' && (
                <div className={`p-4 rounded-lg flex items-center gap-3 ${
                  exportStatus === 'success'
                    ? 'bg-green-50 border border-green-200 text-green-800'
                    : 'bg-red-50 border border-red-200 text-red-800'
                }`}>
                  {exportStatus === 'success' ? (
                    <CheckCircle2 size={20} className="text-green-600" />
                  ) : (
                    <AlertCircle size={20} className="text-red-600" />
                  )}
                  <span className="font-medium">
                    {exportStatus === 'success'
                      ? 'Export completed successfully!'
                      : 'Export failed. Please try again.'}
                  </span>
                </div>
              )}
            </div>
          </div>

          {/* Footer */}
          <div className={`flex-shrink-0 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 p-4 sm:p-6 border-t ${
            darkMode ? 'border-gray-700 bg-gray-800' : 'border-gray-100 bg-gray-50'
          }`}>
            <div className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              {selectedCount > 0 ? (
                <>
                  {selectedCount} conversation{selectedCount !== 1 ? 's' : ''} selected • Plain Text format
                  <br />
                  <span className="text-xs">
                    {getTotalMessages(selectedConversations)} total messages
                  </span>
                </>
              ) : (
                'No conversations selected'
              )}
            </div>

            <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
              <Button
                variant="outline"
                onClick={onClose}
                disabled={isExporting}
                className="w-full sm:w-auto"
              >
                Cancel
              </Button>
              <Button
                onClick={handleExport}
                disabled={selectedCount === 0 || isExporting}
                className="w-full sm:w-auto flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 sm:px-8 py-3 text-base font-semibold"
                size="lg"
              >
                {isExporting ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <Download size={18} />
                )}
                {isExporting ? 'Exporting...' : 'Export Conversations'}
              </Button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}